resources:                                # Which resource types to replicate
  - assets
  - events
  - raw
  - timeseries
  - datapoints
  - files
src_api_key_env_var:                     # Name of environment variable holding CDF API KEY of the source project
dst_api_key_env_var:                     # Name of environment variable holding CDF API KEY of the destination project
src_project:                             # Project that src_api_key belongs to
dst_project:                             # Project that dst_api_key belongs to
resync_destination_tenant: false         # Set to remove objects so destination is in sync with source tenant
delete_if_removed_in_source: false       # Remove object so destination is in sync with source tenant
delete_if_not_replicated: false          # Remove all objects in destination which was created/updated by replication
batch_size: 10000                        # Number of items in each batch
number_of_threads: 1                     # Number of threads to use
datapoint_limit: 1000000                 # Maximum number of datapoints to fetch per time series
client_timeout: 120                      # Seconds for clients to timeout
client_name: cognite-replicator          # Name of client
log_path: log                            # Folder to save logs to
log_level: info                          # Logging level
